//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace baibao.ZipServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="ZipServices.ChinaZipSearchWebServiceSoap")]
    public interface ChinaZipSearchWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://WebXml.com.cn/getSupportProvince", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetSupportProvince(System.AsyncCallback callback, object asyncState);
        
        string[] EndgetSupportProvince(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://WebXml.com.cn/getSupportCity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetSupportCity(string byProvinceName, System.AsyncCallback callback, object asyncState);
        
        string[] EndgetSupportCity(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://WebXml.com.cn/getSupportProvinceCity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetSupportProvinceCity(System.AsyncCallback callback, object asyncState);
        
        baibao.ZipServices.ArrayOfXElement EndgetSupportProvinceCity(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://WebXml.com.cn/getAddressByZipCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetAddressByZipCode(string theZipCode, string userID, System.AsyncCallback callback, object asyncState);
        
        baibao.ZipServices.ArrayOfXElement EndgetAddressByZipCode(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://WebXml.com.cn/getZipCodeByAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetZipCodeByAddress(string theProvinceName, string theCityName, string theAddress, string userID, System.AsyncCallback callback, object asyncState);
        
        baibao.ZipServices.ArrayOfXElement EndgetZipCodeByAddress(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChinaZipSearchWebServiceSoapChannel : baibao.ZipServices.ChinaZipSearchWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getSupportProvinceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getSupportProvinceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getSupportCityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getSupportCityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getSupportProvinceCityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getSupportProvinceCityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public baibao.ZipServices.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((baibao.ZipServices.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getAddressByZipCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getAddressByZipCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public baibao.ZipServices.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((baibao.ZipServices.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getZipCodeByAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getZipCodeByAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public baibao.ZipServices.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((baibao.ZipServices.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChinaZipSearchWebServiceSoapClient : System.ServiceModel.ClientBase<baibao.ZipServices.ChinaZipSearchWebServiceSoap>, baibao.ZipServices.ChinaZipSearchWebServiceSoap {
        
        private BeginOperationDelegate onBegingetSupportProvinceDelegate;
        
        private EndOperationDelegate onEndgetSupportProvinceDelegate;
        
        private System.Threading.SendOrPostCallback ongetSupportProvinceCompletedDelegate;
        
        private BeginOperationDelegate onBegingetSupportCityDelegate;
        
        private EndOperationDelegate onEndgetSupportCityDelegate;
        
        private System.Threading.SendOrPostCallback ongetSupportCityCompletedDelegate;
        
        private BeginOperationDelegate onBegingetSupportProvinceCityDelegate;
        
        private EndOperationDelegate onEndgetSupportProvinceCityDelegate;
        
        private System.Threading.SendOrPostCallback ongetSupportProvinceCityCompletedDelegate;
        
        private BeginOperationDelegate onBegingetAddressByZipCodeDelegate;
        
        private EndOperationDelegate onEndgetAddressByZipCodeDelegate;
        
        private System.Threading.SendOrPostCallback ongetAddressByZipCodeCompletedDelegate;
        
        private BeginOperationDelegate onBegingetZipCodeByAddressDelegate;
        
        private EndOperationDelegate onEndgetZipCodeByAddressDelegate;
        
        private System.Threading.SendOrPostCallback ongetZipCodeByAddressCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ChinaZipSearchWebServiceSoapClient() {
        }
        
        public ChinaZipSearchWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChinaZipSearchWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChinaZipSearchWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChinaZipSearchWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<getSupportProvinceCompletedEventArgs> getSupportProvinceCompleted;
        
        public event System.EventHandler<getSupportCityCompletedEventArgs> getSupportCityCompleted;
        
        public event System.EventHandler<getSupportProvinceCityCompletedEventArgs> getSupportProvinceCityCompleted;
        
        public event System.EventHandler<getAddressByZipCodeCompletedEventArgs> getAddressByZipCodeCompleted;
        
        public event System.EventHandler<getZipCodeByAddressCompletedEventArgs> getZipCodeByAddressCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult baibao.ZipServices.ChinaZipSearchWebServiceSoap.BegingetSupportProvince(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetSupportProvince(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string[] baibao.ZipServices.ChinaZipSearchWebServiceSoap.EndgetSupportProvince(System.IAsyncResult result) {
            return base.Channel.EndgetSupportProvince(result);
        }
        
        private System.IAsyncResult OnBegingetSupportProvince(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((baibao.ZipServices.ChinaZipSearchWebServiceSoap)(this)).BegingetSupportProvince(callback, asyncState);
        }
        
        private object[] OnEndgetSupportProvince(System.IAsyncResult result) {
            string[] retVal = ((baibao.ZipServices.ChinaZipSearchWebServiceSoap)(this)).EndgetSupportProvince(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetSupportProvinceCompleted(object state) {
            if ((this.getSupportProvinceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getSupportProvinceCompleted(this, new getSupportProvinceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getSupportProvinceAsync() {
            this.getSupportProvinceAsync(null);
        }
        
        public void getSupportProvinceAsync(object userState) {
            if ((this.onBegingetSupportProvinceDelegate == null)) {
                this.onBegingetSupportProvinceDelegate = new BeginOperationDelegate(this.OnBegingetSupportProvince);
            }
            if ((this.onEndgetSupportProvinceDelegate == null)) {
                this.onEndgetSupportProvinceDelegate = new EndOperationDelegate(this.OnEndgetSupportProvince);
            }
            if ((this.ongetSupportProvinceCompletedDelegate == null)) {
                this.ongetSupportProvinceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetSupportProvinceCompleted);
            }
            base.InvokeAsync(this.onBegingetSupportProvinceDelegate, null, this.onEndgetSupportProvinceDelegate, this.ongetSupportProvinceCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult baibao.ZipServices.ChinaZipSearchWebServiceSoap.BegingetSupportCity(string byProvinceName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetSupportCity(byProvinceName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string[] baibao.ZipServices.ChinaZipSearchWebServiceSoap.EndgetSupportCity(System.IAsyncResult result) {
            return base.Channel.EndgetSupportCity(result);
        }
        
        private System.IAsyncResult OnBegingetSupportCity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string byProvinceName = ((string)(inValues[0]));
            return ((baibao.ZipServices.ChinaZipSearchWebServiceSoap)(this)).BegingetSupportCity(byProvinceName, callback, asyncState);
        }
        
        private object[] OnEndgetSupportCity(System.IAsyncResult result) {
            string[] retVal = ((baibao.ZipServices.ChinaZipSearchWebServiceSoap)(this)).EndgetSupportCity(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetSupportCityCompleted(object state) {
            if ((this.getSupportCityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getSupportCityCompleted(this, new getSupportCityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getSupportCityAsync(string byProvinceName) {
            this.getSupportCityAsync(byProvinceName, null);
        }
        
        public void getSupportCityAsync(string byProvinceName, object userState) {
            if ((this.onBegingetSupportCityDelegate == null)) {
                this.onBegingetSupportCityDelegate = new BeginOperationDelegate(this.OnBegingetSupportCity);
            }
            if ((this.onEndgetSupportCityDelegate == null)) {
                this.onEndgetSupportCityDelegate = new EndOperationDelegate(this.OnEndgetSupportCity);
            }
            if ((this.ongetSupportCityCompletedDelegate == null)) {
                this.ongetSupportCityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetSupportCityCompleted);
            }
            base.InvokeAsync(this.onBegingetSupportCityDelegate, new object[] {
                        byProvinceName}, this.onEndgetSupportCityDelegate, this.ongetSupportCityCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult baibao.ZipServices.ChinaZipSearchWebServiceSoap.BegingetSupportProvinceCity(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetSupportProvinceCity(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        baibao.ZipServices.ArrayOfXElement baibao.ZipServices.ChinaZipSearchWebServiceSoap.EndgetSupportProvinceCity(System.IAsyncResult result) {
            return base.Channel.EndgetSupportProvinceCity(result);
        }
        
        private System.IAsyncResult OnBegingetSupportProvinceCity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((baibao.ZipServices.ChinaZipSearchWebServiceSoap)(this)).BegingetSupportProvinceCity(callback, asyncState);
        }
        
        private object[] OnEndgetSupportProvinceCity(System.IAsyncResult result) {
            baibao.ZipServices.ArrayOfXElement retVal = ((baibao.ZipServices.ChinaZipSearchWebServiceSoap)(this)).EndgetSupportProvinceCity(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetSupportProvinceCityCompleted(object state) {
            if ((this.getSupportProvinceCityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getSupportProvinceCityCompleted(this, new getSupportProvinceCityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getSupportProvinceCityAsync() {
            this.getSupportProvinceCityAsync(null);
        }
        
        public void getSupportProvinceCityAsync(object userState) {
            if ((this.onBegingetSupportProvinceCityDelegate == null)) {
                this.onBegingetSupportProvinceCityDelegate = new BeginOperationDelegate(this.OnBegingetSupportProvinceCity);
            }
            if ((this.onEndgetSupportProvinceCityDelegate == null)) {
                this.onEndgetSupportProvinceCityDelegate = new EndOperationDelegate(this.OnEndgetSupportProvinceCity);
            }
            if ((this.ongetSupportProvinceCityCompletedDelegate == null)) {
                this.ongetSupportProvinceCityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetSupportProvinceCityCompleted);
            }
            base.InvokeAsync(this.onBegingetSupportProvinceCityDelegate, null, this.onEndgetSupportProvinceCityDelegate, this.ongetSupportProvinceCityCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult baibao.ZipServices.ChinaZipSearchWebServiceSoap.BegingetAddressByZipCode(string theZipCode, string userID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetAddressByZipCode(theZipCode, userID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        baibao.ZipServices.ArrayOfXElement baibao.ZipServices.ChinaZipSearchWebServiceSoap.EndgetAddressByZipCode(System.IAsyncResult result) {
            return base.Channel.EndgetAddressByZipCode(result);
        }
        
        private System.IAsyncResult OnBegingetAddressByZipCode(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string theZipCode = ((string)(inValues[0]));
            string userID = ((string)(inValues[1]));
            return ((baibao.ZipServices.ChinaZipSearchWebServiceSoap)(this)).BegingetAddressByZipCode(theZipCode, userID, callback, asyncState);
        }
        
        private object[] OnEndgetAddressByZipCode(System.IAsyncResult result) {
            baibao.ZipServices.ArrayOfXElement retVal = ((baibao.ZipServices.ChinaZipSearchWebServiceSoap)(this)).EndgetAddressByZipCode(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetAddressByZipCodeCompleted(object state) {
            if ((this.getAddressByZipCodeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getAddressByZipCodeCompleted(this, new getAddressByZipCodeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getAddressByZipCodeAsync(string theZipCode, string userID) {
            this.getAddressByZipCodeAsync(theZipCode, userID, null);
        }
        
        public void getAddressByZipCodeAsync(string theZipCode, string userID, object userState) {
            if ((this.onBegingetAddressByZipCodeDelegate == null)) {
                this.onBegingetAddressByZipCodeDelegate = new BeginOperationDelegate(this.OnBegingetAddressByZipCode);
            }
            if ((this.onEndgetAddressByZipCodeDelegate == null)) {
                this.onEndgetAddressByZipCodeDelegate = new EndOperationDelegate(this.OnEndgetAddressByZipCode);
            }
            if ((this.ongetAddressByZipCodeCompletedDelegate == null)) {
                this.ongetAddressByZipCodeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetAddressByZipCodeCompleted);
            }
            base.InvokeAsync(this.onBegingetAddressByZipCodeDelegate, new object[] {
                        theZipCode,
                        userID}, this.onEndgetAddressByZipCodeDelegate, this.ongetAddressByZipCodeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult baibao.ZipServices.ChinaZipSearchWebServiceSoap.BegingetZipCodeByAddress(string theProvinceName, string theCityName, string theAddress, string userID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetZipCodeByAddress(theProvinceName, theCityName, theAddress, userID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        baibao.ZipServices.ArrayOfXElement baibao.ZipServices.ChinaZipSearchWebServiceSoap.EndgetZipCodeByAddress(System.IAsyncResult result) {
            return base.Channel.EndgetZipCodeByAddress(result);
        }
        
        private System.IAsyncResult OnBegingetZipCodeByAddress(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string theProvinceName = ((string)(inValues[0]));
            string theCityName = ((string)(inValues[1]));
            string theAddress = ((string)(inValues[2]));
            string userID = ((string)(inValues[3]));
            return ((baibao.ZipServices.ChinaZipSearchWebServiceSoap)(this)).BegingetZipCodeByAddress(theProvinceName, theCityName, theAddress, userID, callback, asyncState);
        }
        
        private object[] OnEndgetZipCodeByAddress(System.IAsyncResult result) {
            baibao.ZipServices.ArrayOfXElement retVal = ((baibao.ZipServices.ChinaZipSearchWebServiceSoap)(this)).EndgetZipCodeByAddress(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetZipCodeByAddressCompleted(object state) {
            if ((this.getZipCodeByAddressCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getZipCodeByAddressCompleted(this, new getZipCodeByAddressCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getZipCodeByAddressAsync(string theProvinceName, string theCityName, string theAddress, string userID) {
            this.getZipCodeByAddressAsync(theProvinceName, theCityName, theAddress, userID, null);
        }
        
        public void getZipCodeByAddressAsync(string theProvinceName, string theCityName, string theAddress, string userID, object userState) {
            if ((this.onBegingetZipCodeByAddressDelegate == null)) {
                this.onBegingetZipCodeByAddressDelegate = new BeginOperationDelegate(this.OnBegingetZipCodeByAddress);
            }
            if ((this.onEndgetZipCodeByAddressDelegate == null)) {
                this.onEndgetZipCodeByAddressDelegate = new EndOperationDelegate(this.OnEndgetZipCodeByAddress);
            }
            if ((this.ongetZipCodeByAddressCompletedDelegate == null)) {
                this.ongetZipCodeByAddressCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetZipCodeByAddressCompleted);
            }
            base.InvokeAsync(this.onBegingetZipCodeByAddressDelegate, new object[] {
                        theProvinceName,
                        theCityName,
                        theAddress,
                        userID}, this.onEndgetZipCodeByAddressDelegate, this.ongetZipCodeByAddressCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override baibao.ZipServices.ChinaZipSearchWebServiceSoap CreateChannel() {
            return new ChinaZipSearchWebServiceSoapClientChannel(this);
        }
        
        private class ChinaZipSearchWebServiceSoapClientChannel : ChannelBase<baibao.ZipServices.ChinaZipSearchWebServiceSoap>, baibao.ZipServices.ChinaZipSearchWebServiceSoap {
            
            public ChinaZipSearchWebServiceSoapClientChannel(System.ServiceModel.ClientBase<baibao.ZipServices.ChinaZipSearchWebServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BegingetSupportProvince(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("getSupportProvince", _args, callback, asyncState);
                return _result;
            }
            
            public string[] EndgetSupportProvince(System.IAsyncResult result) {
                object[] _args = new object[0];
                string[] _result = ((string[])(base.EndInvoke("getSupportProvince", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetSupportCity(string byProvinceName, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = byProvinceName;
                System.IAsyncResult _result = base.BeginInvoke("getSupportCity", _args, callback, asyncState);
                return _result;
            }
            
            public string[] EndgetSupportCity(System.IAsyncResult result) {
                object[] _args = new object[0];
                string[] _result = ((string[])(base.EndInvoke("getSupportCity", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetSupportProvinceCity(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("getSupportProvinceCity", _args, callback, asyncState);
                return _result;
            }
            
            public baibao.ZipServices.ArrayOfXElement EndgetSupportProvinceCity(System.IAsyncResult result) {
                object[] _args = new object[0];
                baibao.ZipServices.ArrayOfXElement _result = ((baibao.ZipServices.ArrayOfXElement)(base.EndInvoke("getSupportProvinceCity", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetAddressByZipCode(string theZipCode, string userID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = theZipCode;
                _args[1] = userID;
                System.IAsyncResult _result = base.BeginInvoke("getAddressByZipCode", _args, callback, asyncState);
                return _result;
            }
            
            public baibao.ZipServices.ArrayOfXElement EndgetAddressByZipCode(System.IAsyncResult result) {
                object[] _args = new object[0];
                baibao.ZipServices.ArrayOfXElement _result = ((baibao.ZipServices.ArrayOfXElement)(base.EndInvoke("getAddressByZipCode", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetZipCodeByAddress(string theProvinceName, string theCityName, string theAddress, string userID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = theProvinceName;
                _args[1] = theCityName;
                _args[2] = theAddress;
                _args[3] = userID;
                System.IAsyncResult _result = base.BeginInvoke("getZipCodeByAddress", _args, callback, asyncState);
                return _result;
            }
            
            public baibao.ZipServices.ArrayOfXElement EndgetZipCodeByAddress(System.IAsyncResult result) {
                object[] _args = new object[0];
                baibao.ZipServices.ArrayOfXElement _result = ((baibao.ZipServices.ArrayOfXElement)(base.EndInvoke("getZipCodeByAddress", _args, result)));
                return _result;
            }
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Silverlight.Phone.ServiceReference", "3.7.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement() {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes {
            get {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema() {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer) {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            ) {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader) {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            ) {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element)) {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else {
                    reader.Skip();
                }
            }
        }
    }
}
