//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.261
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace baibao.TvServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="TvServices.ChinaTVprogramWebServiceSoap")]
    public interface ChinaTVprogramWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://WebXml.com.cn/getAreaDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetAreaDataSet(System.AsyncCallback callback, object asyncState);
        
        baibao.TvServices.ArrayOfXElement EndgetAreaDataSet(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://WebXml.com.cn/getAreaString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetAreaString(System.AsyncCallback callback, object asyncState);
        
        string[] EndgetAreaString(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://WebXml.com.cn/getTVstationDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetTVstationDataSet(int theAreaID, System.AsyncCallback callback, object asyncState);
        
        baibao.TvServices.ArrayOfXElement EndgetTVstationDataSet(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://WebXml.com.cn/getTVstationString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetTVstationString(int theAreaID, System.AsyncCallback callback, object asyncState);
        
        string[] EndgetTVstationString(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://WebXml.com.cn/getTVchannelDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetTVchannelDataSet(int theTVstationID, System.AsyncCallback callback, object asyncState);
        
        baibao.TvServices.ArrayOfXElement EndgetTVchannelDataSet(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://WebXml.com.cn/getTVchannelString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetTVchannelString(int theTVstationID, System.AsyncCallback callback, object asyncState);
        
        string[] EndgetTVchannelString(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://WebXml.com.cn/getTVprogramDateSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetTVprogramDateSet(int theTVchannelID, string theDate, string userID, System.AsyncCallback callback, object asyncState);
        
        baibao.TvServices.ArrayOfXElement EndgetTVprogramDateSet(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://WebXml.com.cn/getTVprogramString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetTVprogramString(int theTVchannelID, string theDate, string userID, System.AsyncCallback callback, object asyncState);
        
        string[] EndgetTVprogramString(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChinaTVprogramWebServiceSoapChannel : baibao.TvServices.ChinaTVprogramWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getAreaDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getAreaDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public baibao.TvServices.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((baibao.TvServices.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getAreaStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getAreaStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getTVstationDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getTVstationDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public baibao.TvServices.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((baibao.TvServices.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getTVstationStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getTVstationStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getTVchannelDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getTVchannelDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public baibao.TvServices.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((baibao.TvServices.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getTVchannelStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getTVchannelStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getTVprogramDateSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getTVprogramDateSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public baibao.TvServices.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((baibao.TvServices.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getTVprogramStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getTVprogramStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChinaTVprogramWebServiceSoapClient : System.ServiceModel.ClientBase<baibao.TvServices.ChinaTVprogramWebServiceSoap>, baibao.TvServices.ChinaTVprogramWebServiceSoap {
        
        private BeginOperationDelegate onBegingetAreaDataSetDelegate;
        
        private EndOperationDelegate onEndgetAreaDataSetDelegate;
        
        private System.Threading.SendOrPostCallback ongetAreaDataSetCompletedDelegate;
        
        private BeginOperationDelegate onBegingetAreaStringDelegate;
        
        private EndOperationDelegate onEndgetAreaStringDelegate;
        
        private System.Threading.SendOrPostCallback ongetAreaStringCompletedDelegate;
        
        private BeginOperationDelegate onBegingetTVstationDataSetDelegate;
        
        private EndOperationDelegate onEndgetTVstationDataSetDelegate;
        
        private System.Threading.SendOrPostCallback ongetTVstationDataSetCompletedDelegate;
        
        private BeginOperationDelegate onBegingetTVstationStringDelegate;
        
        private EndOperationDelegate onEndgetTVstationStringDelegate;
        
        private System.Threading.SendOrPostCallback ongetTVstationStringCompletedDelegate;
        
        private BeginOperationDelegate onBegingetTVchannelDataSetDelegate;
        
        private EndOperationDelegate onEndgetTVchannelDataSetDelegate;
        
        private System.Threading.SendOrPostCallback ongetTVchannelDataSetCompletedDelegate;
        
        private BeginOperationDelegate onBegingetTVchannelStringDelegate;
        
        private EndOperationDelegate onEndgetTVchannelStringDelegate;
        
        private System.Threading.SendOrPostCallback ongetTVchannelStringCompletedDelegate;
        
        private BeginOperationDelegate onBegingetTVprogramDateSetDelegate;
        
        private EndOperationDelegate onEndgetTVprogramDateSetDelegate;
        
        private System.Threading.SendOrPostCallback ongetTVprogramDateSetCompletedDelegate;
        
        private BeginOperationDelegate onBegingetTVprogramStringDelegate;
        
        private EndOperationDelegate onEndgetTVprogramStringDelegate;
        
        private System.Threading.SendOrPostCallback ongetTVprogramStringCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ChinaTVprogramWebServiceSoapClient() {
        }
        
        public ChinaTVprogramWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChinaTVprogramWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChinaTVprogramWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChinaTVprogramWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<getAreaDataSetCompletedEventArgs> getAreaDataSetCompleted;
        
        public event System.EventHandler<getAreaStringCompletedEventArgs> getAreaStringCompleted;
        
        public event System.EventHandler<getTVstationDataSetCompletedEventArgs> getTVstationDataSetCompleted;
        
        public event System.EventHandler<getTVstationStringCompletedEventArgs> getTVstationStringCompleted;
        
        public event System.EventHandler<getTVchannelDataSetCompletedEventArgs> getTVchannelDataSetCompleted;
        
        public event System.EventHandler<getTVchannelStringCompletedEventArgs> getTVchannelStringCompleted;
        
        public event System.EventHandler<getTVprogramDateSetCompletedEventArgs> getTVprogramDateSetCompleted;
        
        public event System.EventHandler<getTVprogramStringCompletedEventArgs> getTVprogramStringCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult baibao.TvServices.ChinaTVprogramWebServiceSoap.BegingetAreaDataSet(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetAreaDataSet(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        baibao.TvServices.ArrayOfXElement baibao.TvServices.ChinaTVprogramWebServiceSoap.EndgetAreaDataSet(System.IAsyncResult result) {
            return base.Channel.EndgetAreaDataSet(result);
        }
        
        private System.IAsyncResult OnBegingetAreaDataSet(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((baibao.TvServices.ChinaTVprogramWebServiceSoap)(this)).BegingetAreaDataSet(callback, asyncState);
        }
        
        private object[] OnEndgetAreaDataSet(System.IAsyncResult result) {
            baibao.TvServices.ArrayOfXElement retVal = ((baibao.TvServices.ChinaTVprogramWebServiceSoap)(this)).EndgetAreaDataSet(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetAreaDataSetCompleted(object state) {
            if ((this.getAreaDataSetCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getAreaDataSetCompleted(this, new getAreaDataSetCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getAreaDataSetAsync() {
            this.getAreaDataSetAsync(null);
        }
        
        public void getAreaDataSetAsync(object userState) {
            if ((this.onBegingetAreaDataSetDelegate == null)) {
                this.onBegingetAreaDataSetDelegate = new BeginOperationDelegate(this.OnBegingetAreaDataSet);
            }
            if ((this.onEndgetAreaDataSetDelegate == null)) {
                this.onEndgetAreaDataSetDelegate = new EndOperationDelegate(this.OnEndgetAreaDataSet);
            }
            if ((this.ongetAreaDataSetCompletedDelegate == null)) {
                this.ongetAreaDataSetCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetAreaDataSetCompleted);
            }
            base.InvokeAsync(this.onBegingetAreaDataSetDelegate, null, this.onEndgetAreaDataSetDelegate, this.ongetAreaDataSetCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult baibao.TvServices.ChinaTVprogramWebServiceSoap.BegingetAreaString(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetAreaString(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string[] baibao.TvServices.ChinaTVprogramWebServiceSoap.EndgetAreaString(System.IAsyncResult result) {
            return base.Channel.EndgetAreaString(result);
        }
        
        private System.IAsyncResult OnBegingetAreaString(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((baibao.TvServices.ChinaTVprogramWebServiceSoap)(this)).BegingetAreaString(callback, asyncState);
        }
        
        private object[] OnEndgetAreaString(System.IAsyncResult result) {
            string[] retVal = ((baibao.TvServices.ChinaTVprogramWebServiceSoap)(this)).EndgetAreaString(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetAreaStringCompleted(object state) {
            if ((this.getAreaStringCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getAreaStringCompleted(this, new getAreaStringCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getAreaStringAsync() {
            this.getAreaStringAsync(null);
        }
        
        public void getAreaStringAsync(object userState) {
            if ((this.onBegingetAreaStringDelegate == null)) {
                this.onBegingetAreaStringDelegate = new BeginOperationDelegate(this.OnBegingetAreaString);
            }
            if ((this.onEndgetAreaStringDelegate == null)) {
                this.onEndgetAreaStringDelegate = new EndOperationDelegate(this.OnEndgetAreaString);
            }
            if ((this.ongetAreaStringCompletedDelegate == null)) {
                this.ongetAreaStringCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetAreaStringCompleted);
            }
            base.InvokeAsync(this.onBegingetAreaStringDelegate, null, this.onEndgetAreaStringDelegate, this.ongetAreaStringCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult baibao.TvServices.ChinaTVprogramWebServiceSoap.BegingetTVstationDataSet(int theAreaID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetTVstationDataSet(theAreaID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        baibao.TvServices.ArrayOfXElement baibao.TvServices.ChinaTVprogramWebServiceSoap.EndgetTVstationDataSet(System.IAsyncResult result) {
            return base.Channel.EndgetTVstationDataSet(result);
        }
        
        private System.IAsyncResult OnBegingetTVstationDataSet(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int theAreaID = ((int)(inValues[0]));
            return ((baibao.TvServices.ChinaTVprogramWebServiceSoap)(this)).BegingetTVstationDataSet(theAreaID, callback, asyncState);
        }
        
        private object[] OnEndgetTVstationDataSet(System.IAsyncResult result) {
            baibao.TvServices.ArrayOfXElement retVal = ((baibao.TvServices.ChinaTVprogramWebServiceSoap)(this)).EndgetTVstationDataSet(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetTVstationDataSetCompleted(object state) {
            if ((this.getTVstationDataSetCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getTVstationDataSetCompleted(this, new getTVstationDataSetCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getTVstationDataSetAsync(int theAreaID) {
            this.getTVstationDataSetAsync(theAreaID, null);
        }
        
        public void getTVstationDataSetAsync(int theAreaID, object userState) {
            if ((this.onBegingetTVstationDataSetDelegate == null)) {
                this.onBegingetTVstationDataSetDelegate = new BeginOperationDelegate(this.OnBegingetTVstationDataSet);
            }
            if ((this.onEndgetTVstationDataSetDelegate == null)) {
                this.onEndgetTVstationDataSetDelegate = new EndOperationDelegate(this.OnEndgetTVstationDataSet);
            }
            if ((this.ongetTVstationDataSetCompletedDelegate == null)) {
                this.ongetTVstationDataSetCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetTVstationDataSetCompleted);
            }
            base.InvokeAsync(this.onBegingetTVstationDataSetDelegate, new object[] {
                        theAreaID}, this.onEndgetTVstationDataSetDelegate, this.ongetTVstationDataSetCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult baibao.TvServices.ChinaTVprogramWebServiceSoap.BegingetTVstationString(int theAreaID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetTVstationString(theAreaID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string[] baibao.TvServices.ChinaTVprogramWebServiceSoap.EndgetTVstationString(System.IAsyncResult result) {
            return base.Channel.EndgetTVstationString(result);
        }
        
        private System.IAsyncResult OnBegingetTVstationString(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int theAreaID = ((int)(inValues[0]));
            return ((baibao.TvServices.ChinaTVprogramWebServiceSoap)(this)).BegingetTVstationString(theAreaID, callback, asyncState);
        }
        
        private object[] OnEndgetTVstationString(System.IAsyncResult result) {
            string[] retVal = ((baibao.TvServices.ChinaTVprogramWebServiceSoap)(this)).EndgetTVstationString(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetTVstationStringCompleted(object state) {
            if ((this.getTVstationStringCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getTVstationStringCompleted(this, new getTVstationStringCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getTVstationStringAsync(int theAreaID) {
            this.getTVstationStringAsync(theAreaID, null);
        }
        
        public void getTVstationStringAsync(int theAreaID, object userState) {
            if ((this.onBegingetTVstationStringDelegate == null)) {
                this.onBegingetTVstationStringDelegate = new BeginOperationDelegate(this.OnBegingetTVstationString);
            }
            if ((this.onEndgetTVstationStringDelegate == null)) {
                this.onEndgetTVstationStringDelegate = new EndOperationDelegate(this.OnEndgetTVstationString);
            }
            if ((this.ongetTVstationStringCompletedDelegate == null)) {
                this.ongetTVstationStringCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetTVstationStringCompleted);
            }
            base.InvokeAsync(this.onBegingetTVstationStringDelegate, new object[] {
                        theAreaID}, this.onEndgetTVstationStringDelegate, this.ongetTVstationStringCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult baibao.TvServices.ChinaTVprogramWebServiceSoap.BegingetTVchannelDataSet(int theTVstationID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetTVchannelDataSet(theTVstationID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        baibao.TvServices.ArrayOfXElement baibao.TvServices.ChinaTVprogramWebServiceSoap.EndgetTVchannelDataSet(System.IAsyncResult result) {
            return base.Channel.EndgetTVchannelDataSet(result);
        }
        
        private System.IAsyncResult OnBegingetTVchannelDataSet(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int theTVstationID = ((int)(inValues[0]));
            return ((baibao.TvServices.ChinaTVprogramWebServiceSoap)(this)).BegingetTVchannelDataSet(theTVstationID, callback, asyncState);
        }
        
        private object[] OnEndgetTVchannelDataSet(System.IAsyncResult result) {
            baibao.TvServices.ArrayOfXElement retVal = ((baibao.TvServices.ChinaTVprogramWebServiceSoap)(this)).EndgetTVchannelDataSet(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetTVchannelDataSetCompleted(object state) {
            if ((this.getTVchannelDataSetCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getTVchannelDataSetCompleted(this, new getTVchannelDataSetCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getTVchannelDataSetAsync(int theTVstationID) {
            this.getTVchannelDataSetAsync(theTVstationID, null);
        }
        
        public void getTVchannelDataSetAsync(int theTVstationID, object userState) {
            if ((this.onBegingetTVchannelDataSetDelegate == null)) {
                this.onBegingetTVchannelDataSetDelegate = new BeginOperationDelegate(this.OnBegingetTVchannelDataSet);
            }
            if ((this.onEndgetTVchannelDataSetDelegate == null)) {
                this.onEndgetTVchannelDataSetDelegate = new EndOperationDelegate(this.OnEndgetTVchannelDataSet);
            }
            if ((this.ongetTVchannelDataSetCompletedDelegate == null)) {
                this.ongetTVchannelDataSetCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetTVchannelDataSetCompleted);
            }
            base.InvokeAsync(this.onBegingetTVchannelDataSetDelegate, new object[] {
                        theTVstationID}, this.onEndgetTVchannelDataSetDelegate, this.ongetTVchannelDataSetCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult baibao.TvServices.ChinaTVprogramWebServiceSoap.BegingetTVchannelString(int theTVstationID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetTVchannelString(theTVstationID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string[] baibao.TvServices.ChinaTVprogramWebServiceSoap.EndgetTVchannelString(System.IAsyncResult result) {
            return base.Channel.EndgetTVchannelString(result);
        }
        
        private System.IAsyncResult OnBegingetTVchannelString(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int theTVstationID = ((int)(inValues[0]));
            return ((baibao.TvServices.ChinaTVprogramWebServiceSoap)(this)).BegingetTVchannelString(theTVstationID, callback, asyncState);
        }
        
        private object[] OnEndgetTVchannelString(System.IAsyncResult result) {
            string[] retVal = ((baibao.TvServices.ChinaTVprogramWebServiceSoap)(this)).EndgetTVchannelString(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetTVchannelStringCompleted(object state) {
            if ((this.getTVchannelStringCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getTVchannelStringCompleted(this, new getTVchannelStringCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getTVchannelStringAsync(int theTVstationID) {
            this.getTVchannelStringAsync(theTVstationID, null);
        }
        
        public void getTVchannelStringAsync(int theTVstationID, object userState) {
            if ((this.onBegingetTVchannelStringDelegate == null)) {
                this.onBegingetTVchannelStringDelegate = new BeginOperationDelegate(this.OnBegingetTVchannelString);
            }
            if ((this.onEndgetTVchannelStringDelegate == null)) {
                this.onEndgetTVchannelStringDelegate = new EndOperationDelegate(this.OnEndgetTVchannelString);
            }
            if ((this.ongetTVchannelStringCompletedDelegate == null)) {
                this.ongetTVchannelStringCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetTVchannelStringCompleted);
            }
            base.InvokeAsync(this.onBegingetTVchannelStringDelegate, new object[] {
                        theTVstationID}, this.onEndgetTVchannelStringDelegate, this.ongetTVchannelStringCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult baibao.TvServices.ChinaTVprogramWebServiceSoap.BegingetTVprogramDateSet(int theTVchannelID, string theDate, string userID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetTVprogramDateSet(theTVchannelID, theDate, userID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        baibao.TvServices.ArrayOfXElement baibao.TvServices.ChinaTVprogramWebServiceSoap.EndgetTVprogramDateSet(System.IAsyncResult result) {
            return base.Channel.EndgetTVprogramDateSet(result);
        }
        
        private System.IAsyncResult OnBegingetTVprogramDateSet(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int theTVchannelID = ((int)(inValues[0]));
            string theDate = ((string)(inValues[1]));
            string userID = ((string)(inValues[2]));
            return ((baibao.TvServices.ChinaTVprogramWebServiceSoap)(this)).BegingetTVprogramDateSet(theTVchannelID, theDate, userID, callback, asyncState);
        }
        
        private object[] OnEndgetTVprogramDateSet(System.IAsyncResult result) {
            baibao.TvServices.ArrayOfXElement retVal = ((baibao.TvServices.ChinaTVprogramWebServiceSoap)(this)).EndgetTVprogramDateSet(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetTVprogramDateSetCompleted(object state) {
            if ((this.getTVprogramDateSetCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getTVprogramDateSetCompleted(this, new getTVprogramDateSetCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getTVprogramDateSetAsync(int theTVchannelID, string theDate, string userID) {
            this.getTVprogramDateSetAsync(theTVchannelID, theDate, userID, null);
        }
        
        public void getTVprogramDateSetAsync(int theTVchannelID, string theDate, string userID, object userState) {
            if ((this.onBegingetTVprogramDateSetDelegate == null)) {
                this.onBegingetTVprogramDateSetDelegate = new BeginOperationDelegate(this.OnBegingetTVprogramDateSet);
            }
            if ((this.onEndgetTVprogramDateSetDelegate == null)) {
                this.onEndgetTVprogramDateSetDelegate = new EndOperationDelegate(this.OnEndgetTVprogramDateSet);
            }
            if ((this.ongetTVprogramDateSetCompletedDelegate == null)) {
                this.ongetTVprogramDateSetCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetTVprogramDateSetCompleted);
            }
            base.InvokeAsync(this.onBegingetTVprogramDateSetDelegate, new object[] {
                        theTVchannelID,
                        theDate,
                        userID}, this.onEndgetTVprogramDateSetDelegate, this.ongetTVprogramDateSetCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult baibao.TvServices.ChinaTVprogramWebServiceSoap.BegingetTVprogramString(int theTVchannelID, string theDate, string userID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetTVprogramString(theTVchannelID, theDate, userID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string[] baibao.TvServices.ChinaTVprogramWebServiceSoap.EndgetTVprogramString(System.IAsyncResult result) {
            return base.Channel.EndgetTVprogramString(result);
        }
        
        private System.IAsyncResult OnBegingetTVprogramString(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int theTVchannelID = ((int)(inValues[0]));
            string theDate = ((string)(inValues[1]));
            string userID = ((string)(inValues[2]));
            return ((baibao.TvServices.ChinaTVprogramWebServiceSoap)(this)).BegingetTVprogramString(theTVchannelID, theDate, userID, callback, asyncState);
        }
        
        private object[] OnEndgetTVprogramString(System.IAsyncResult result) {
            string[] retVal = ((baibao.TvServices.ChinaTVprogramWebServiceSoap)(this)).EndgetTVprogramString(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetTVprogramStringCompleted(object state) {
            if ((this.getTVprogramStringCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getTVprogramStringCompleted(this, new getTVprogramStringCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getTVprogramStringAsync(int theTVchannelID, string theDate, string userID) {
            this.getTVprogramStringAsync(theTVchannelID, theDate, userID, null);
        }
        
        public void getTVprogramStringAsync(int theTVchannelID, string theDate, string userID, object userState) {
            if ((this.onBegingetTVprogramStringDelegate == null)) {
                this.onBegingetTVprogramStringDelegate = new BeginOperationDelegate(this.OnBegingetTVprogramString);
            }
            if ((this.onEndgetTVprogramStringDelegate == null)) {
                this.onEndgetTVprogramStringDelegate = new EndOperationDelegate(this.OnEndgetTVprogramString);
            }
            if ((this.ongetTVprogramStringCompletedDelegate == null)) {
                this.ongetTVprogramStringCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetTVprogramStringCompleted);
            }
            base.InvokeAsync(this.onBegingetTVprogramStringDelegate, new object[] {
                        theTVchannelID,
                        theDate,
                        userID}, this.onEndgetTVprogramStringDelegate, this.ongetTVprogramStringCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override baibao.TvServices.ChinaTVprogramWebServiceSoap CreateChannel() {
            return new ChinaTVprogramWebServiceSoapClientChannel(this);
        }
        
        private class ChinaTVprogramWebServiceSoapClientChannel : ChannelBase<baibao.TvServices.ChinaTVprogramWebServiceSoap>, baibao.TvServices.ChinaTVprogramWebServiceSoap {
            
            public ChinaTVprogramWebServiceSoapClientChannel(System.ServiceModel.ClientBase<baibao.TvServices.ChinaTVprogramWebServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BegingetAreaDataSet(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("getAreaDataSet", _args, callback, asyncState);
                return _result;
            }
            
            public baibao.TvServices.ArrayOfXElement EndgetAreaDataSet(System.IAsyncResult result) {
                object[] _args = new object[0];
                baibao.TvServices.ArrayOfXElement _result = ((baibao.TvServices.ArrayOfXElement)(base.EndInvoke("getAreaDataSet", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetAreaString(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("getAreaString", _args, callback, asyncState);
                return _result;
            }
            
            public string[] EndgetAreaString(System.IAsyncResult result) {
                object[] _args = new object[0];
                string[] _result = ((string[])(base.EndInvoke("getAreaString", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetTVstationDataSet(int theAreaID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = theAreaID;
                System.IAsyncResult _result = base.BeginInvoke("getTVstationDataSet", _args, callback, asyncState);
                return _result;
            }
            
            public baibao.TvServices.ArrayOfXElement EndgetTVstationDataSet(System.IAsyncResult result) {
                object[] _args = new object[0];
                baibao.TvServices.ArrayOfXElement _result = ((baibao.TvServices.ArrayOfXElement)(base.EndInvoke("getTVstationDataSet", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetTVstationString(int theAreaID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = theAreaID;
                System.IAsyncResult _result = base.BeginInvoke("getTVstationString", _args, callback, asyncState);
                return _result;
            }
            
            public string[] EndgetTVstationString(System.IAsyncResult result) {
                object[] _args = new object[0];
                string[] _result = ((string[])(base.EndInvoke("getTVstationString", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetTVchannelDataSet(int theTVstationID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = theTVstationID;
                System.IAsyncResult _result = base.BeginInvoke("getTVchannelDataSet", _args, callback, asyncState);
                return _result;
            }
            
            public baibao.TvServices.ArrayOfXElement EndgetTVchannelDataSet(System.IAsyncResult result) {
                object[] _args = new object[0];
                baibao.TvServices.ArrayOfXElement _result = ((baibao.TvServices.ArrayOfXElement)(base.EndInvoke("getTVchannelDataSet", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetTVchannelString(int theTVstationID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = theTVstationID;
                System.IAsyncResult _result = base.BeginInvoke("getTVchannelString", _args, callback, asyncState);
                return _result;
            }
            
            public string[] EndgetTVchannelString(System.IAsyncResult result) {
                object[] _args = new object[0];
                string[] _result = ((string[])(base.EndInvoke("getTVchannelString", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetTVprogramDateSet(int theTVchannelID, string theDate, string userID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = theTVchannelID;
                _args[1] = theDate;
                _args[2] = userID;
                System.IAsyncResult _result = base.BeginInvoke("getTVprogramDateSet", _args, callback, asyncState);
                return _result;
            }
            
            public baibao.TvServices.ArrayOfXElement EndgetTVprogramDateSet(System.IAsyncResult result) {
                object[] _args = new object[0];
                baibao.TvServices.ArrayOfXElement _result = ((baibao.TvServices.ArrayOfXElement)(base.EndInvoke("getTVprogramDateSet", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetTVprogramString(int theTVchannelID, string theDate, string userID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = theTVchannelID;
                _args[1] = theDate;
                _args[2] = userID;
                System.IAsyncResult _result = base.BeginInvoke("getTVprogramString", _args, callback, asyncState);
                return _result;
            }
            
            public string[] EndgetTVprogramString(System.IAsyncResult result) {
                object[] _args = new object[0];
                string[] _result = ((string[])(base.EndInvoke("getTVprogramString", _args, result)));
                return _result;
            }
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Silverlight.Phone.ServiceReference", "3.7.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement() {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes {
            get {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema() {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer) {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            ) {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader) {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            ) {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element)) {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else {
                    reader.Skip();
                }
            }
        }
    }
}
