//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace baibao.QQServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="QQServices.qqOnlineWebServiceSoap")]
    public interface qqOnlineWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://WebXml.com.cn/qqCheckOnline", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginqqCheckOnline(string qqCode, System.AsyncCallback callback, object asyncState);
        
        string EndqqCheckOnline(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface qqOnlineWebServiceSoapChannel : baibao.QQServices.qqOnlineWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class qqCheckOnlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public qqCheckOnlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class qqOnlineWebServiceSoapClient : System.ServiceModel.ClientBase<baibao.QQServices.qqOnlineWebServiceSoap>, baibao.QQServices.qqOnlineWebServiceSoap {
        
        private BeginOperationDelegate onBeginqqCheckOnlineDelegate;
        
        private EndOperationDelegate onEndqqCheckOnlineDelegate;
        
        private System.Threading.SendOrPostCallback onqqCheckOnlineCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public qqOnlineWebServiceSoapClient() {
        }
        
        public qqOnlineWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public qqOnlineWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public qqOnlineWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public qqOnlineWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<qqCheckOnlineCompletedEventArgs> qqCheckOnlineCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult baibao.QQServices.qqOnlineWebServiceSoap.BeginqqCheckOnline(string qqCode, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginqqCheckOnline(qqCode, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string baibao.QQServices.qqOnlineWebServiceSoap.EndqqCheckOnline(System.IAsyncResult result) {
            return base.Channel.EndqqCheckOnline(result);
        }
        
        private System.IAsyncResult OnBeginqqCheckOnline(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string qqCode = ((string)(inValues[0]));
            return ((baibao.QQServices.qqOnlineWebServiceSoap)(this)).BeginqqCheckOnline(qqCode, callback, asyncState);
        }
        
        private object[] OnEndqqCheckOnline(System.IAsyncResult result) {
            string retVal = ((baibao.QQServices.qqOnlineWebServiceSoap)(this)).EndqqCheckOnline(result);
            return new object[] {
                    retVal};
        }
        
        private void OnqqCheckOnlineCompleted(object state) {
            if ((this.qqCheckOnlineCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.qqCheckOnlineCompleted(this, new qqCheckOnlineCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void qqCheckOnlineAsync(string qqCode) {
            this.qqCheckOnlineAsync(qqCode, null);
        }
        
        public void qqCheckOnlineAsync(string qqCode, object userState) {
            if ((this.onBeginqqCheckOnlineDelegate == null)) {
                this.onBeginqqCheckOnlineDelegate = new BeginOperationDelegate(this.OnBeginqqCheckOnline);
            }
            if ((this.onEndqqCheckOnlineDelegate == null)) {
                this.onEndqqCheckOnlineDelegate = new EndOperationDelegate(this.OnEndqqCheckOnline);
            }
            if ((this.onqqCheckOnlineCompletedDelegate == null)) {
                this.onqqCheckOnlineCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnqqCheckOnlineCompleted);
            }
            base.InvokeAsync(this.onBeginqqCheckOnlineDelegate, new object[] {
                        qqCode}, this.onEndqqCheckOnlineDelegate, this.onqqCheckOnlineCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override baibao.QQServices.qqOnlineWebServiceSoap CreateChannel() {
            return new qqOnlineWebServiceSoapClientChannel(this);
        }
        
        private class qqOnlineWebServiceSoapClientChannel : ChannelBase<baibao.QQServices.qqOnlineWebServiceSoap>, baibao.QQServices.qqOnlineWebServiceSoap {
            
            public qqOnlineWebServiceSoapClientChannel(System.ServiceModel.ClientBase<baibao.QQServices.qqOnlineWebServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginqqCheckOnline(string qqCode, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = qqCode;
                System.IAsyncResult _result = base.BeginInvoke("qqCheckOnline", _args, callback, asyncState);
                return _result;
            }
            
            public string EndqqCheckOnline(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("qqCheckOnline", _args, result)));
                return _result;
            }
        }
    }
}
